name: beorganized
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  calendar_date_picker2: ^1.1.7
  sqflite: ^2.3.3+2
  mobx: ^2.3.3+2
  slideable: ^0.0.2
  provider: ^6.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
